# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc540d9ce0dc4319659660af0a59cb31b2fa59203699f04cf53b9963ba8fde8ab3c4c5ed4879c959979b32201c6860a7509ac111369edd20247d27799b2a4f1f

test:
  secret_key_base: 089056c8064bb8ff7d6572253bda83b8c02d4e96290af9cf950b62dd13adb15271193a92ae51ec717f239537460e61d6aafc4bb9a0814555ab38362dc832d186

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
